// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql"
	"time"
)

type GoInstructor struct {
	InstructorID           int64
	InstructorDepartmentID int16
	InstructorHireDate     time.Time
	InstructorTitle        string
	UserID                 int64
}

type GoOperator struct {
	OperatorID       int64
	OperatorHireDate time.Time
	OperatorUnitName string
	UserID           int64
}

type GoStudent struct {
	StudentID             int64
	StudentCredit         int16
	StudentEnrollmentYear int16
	StudentGpa            string
	StudentDepartmentID   int16
	UserID                int64
}

type GoUser struct {
	UserID        int32
	UserAccount   string
	UserPassword  string
	UserEmail     string
	UserName      string
	UserPhone     string
	UserSalt      string
	UserCreatedAt sql.NullTime
	UserUpdatedAt sql.NullTime
}
