server:
  port: 8000
  mode: dev

postgresql:
  host: "127.0.0.1"
  port: 5432
  username: root
  password: root123
  dbname: hcmut
  sslmode: disable

logger:
  log_level: debug
  file_log_name: ./storages/logs/dev.log
  max_backups: 30
  max_age: 7
  max_size: 1024
  compress: true

redis:
  host: localhost
  port: 6379
  password:
  database: 0

rabbitmq:
  user: guest
  password: guest
  host: 127.0.0.1
  port: 5672

jwt:
  TOKEN_HOUR_LIFESPAN: 1
  JWT_EXPIRATION: 1h
  API_SECRET: "hcmut"
