version: "3.2"

networks:
  local-networks:
    driver: bridge

volumes:
  rabbitmq_data:

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: hcmut
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres_data:/var/lib/postgres/data
      - ./postgres/init:/docker-entrypoint-initdb.d/
    networks:
      - local-networks

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis_data:/data
    networks:
      - local-networks

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - local-networks
