// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
)

type GoUser struct {
	ID        int32
	Email     string
	Phone     string
	Username  string
	Password  string
	Salt      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
