// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
)

type GoUser struct {
	UserID        int32
	UserAccount   string
	UserPassword  string
	UserEmail     string
	UserName      string
	UserPhone     string
	UserCredit    int16
	UserSalt      string
	UserCreatedAt sql.NullTime
	UserUpdatedAt sql.NullTime
}
