// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"
)

type GoCourse struct {
	CourseID          int32
	SubjectID         string
	CourseTerm        string
	CourseMaxSlot     int16
	CourseCurrentSlot int16
	CourseCreatedAt   sql.NullTime
	CourseUpdatedAt   sql.NullTime
}

type GoInstructor struct {
	InstructorID           int64
	InstructorDepartmentID int16
	InstructorHireDate     time.Time
	InstructorTitle        string
	UserID                 int64
}

type GoOperator struct {
	OperatorID       int64
	OperatorHireDate time.Time
	OperatorUnitName string
	UserID           int64
}

type GoPermission struct {
	PermissionID        int32
	PermissionName      sql.NullString
	PermissionCreatedAt sql.NullTime
	PermissionUpdatedAt sql.NullTime
}

type GoRegistration struct {
	RegistrationID     int64
	StudentID          int64
	CourseID           int32
	RegistrationStatus string
	RegistrationDate   sql.NullTime
}

type GoRole struct {
	RoleID        int32
	RoleName      sql.NullString
	RoleCreatedAt sql.NullTime
	RoleUpdatedAt sql.NullTime
}

type GoRolePermission struct {
	RoleID                  int32
	PermissionID            int32
	RolePermissionCreatedAt sql.NullTime
	RolePermissionUpdatedAt sql.NullTime
}

type GoStudent struct {
	StudentID             int64
	StudentCredit         int16
	StudentEnrollmentYear int16
	StudentGpa            string
	StudentDepartmentID   int16
	UserID                int64
}

type GoSubject struct {
	SubjectID     string
	SubjectTitle  string
	SubjectCredit int16
	SubjectNote   sql.NullString
}

type GoSubjectRequirement struct {
	SubjectID       string
	RequirementID   string
	RequirementType sql.NullString
}

type GoUser struct {
	UserID        int32
	UserAccount   string
	UserPassword  string
	UserEmail     string
	UserName      string
	UserPhone     string
	UserSalt      string
	UserCreatedAt sql.NullTime
	UserUpdatedAt sql.NullTime
}

type GoUserRole struct {
	UserID            int32
	RoleID            int32
	UserRoleCreatedAt sql.NullTime
	UserRoleUpdatedAt sql.NullTime
}
