FROM golang:alpine AS builder
RUN apk add --no-cache git
RUN go install github.com/pressly/goose/v3/cmd/goose@latest

FROM alpine
COPY --from=builder /go/bin/goose /usr/local/bin/goose
COPY schema /migrations
WORKDIR /migrations