networks:
  local-networks:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: hcmut
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres_data:/var/lib/postgres/data
      - ./postgres/init:/docker-entrypoint-initdb.d/
    networks:
      - local-networks

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis_data:/data
    networks:
      - local-networks
